language: scala
scala:
   - 2.11.8
   - 2.12.1
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - postgresql
  - mysql
cache:
  directories:
    - vendor/bundle
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
before_script:
  - ./script/prepare_build.sh
script:
  - sbt +test
