# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "0.3.x" ]
  pull_request:
    branches: [ "0.3.x" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGUSER: postgres
      MYSQLV: '5.7'
      PGV: '15'
    strategy:
     matrix:
       scala: [2.13.12, 3.3.1]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Start postgresql & mysql
        working-directory: build/server
        run:
          docker-compose up -d && docker-compose logs

      - name: Setup database
        run: bash build/prepare_build.sh

      - name: Run tests
        run: sbt ++${{matrix.scala}} test
