# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "0.3.x" ]
  pull_request:
    branches: [ "0.3.x" ]

permissions:
  contents: read

jobs:
  build:


    runs-on: ubuntu-latest
    env:
      PGUSER: postgres
      MYSQLV: '5.7'
      PGV: '9.6'
    strategy:
     matrix:
       scala: [2.13.10, 3.2.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Start postgresql & mysql
        working-directory: build/server
        run:
          docker-compose up -d && docker-compose logs
    - name: Setup database
        run: bash build/prepare_build.sh
    - name: Run tests
      run: sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
